### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by killedWithFire9001** [SinonBot/Sinon-Rebirth#1]
-- Core
- [x] seamless total update
- [x] auto update from git
- [x] fallback update system
- [x] fallback error handling
- [x] deps via NPM install
- [x] prefixing
- [ ] database core
- [x] dev perms
- [ ] supporter perms
- [x] (commander perms or a diff method?)
